// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DownUp: typeof import('./src/components/DownUp.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Mine: typeof import('./src/components/Mine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Top: typeof import('./src/components/Top.vue')['default']
    Video: typeof import('./src/components/Video.vue')['default']
  }
}
